
const CONSTANTS = {
  GRACE_FULL_KILL_TIMEOUT: 1600,
  GRACE_FULL_KILL_MSG_TIMEOUT: 1500,
  PERMISSION: {
    USER_AUTHENTICATION: {},
    GUEST_USER: {},
    AGENCY: {}
  },
  METER_TO_STATUTE_MILES: 0.0006213711922373
}
module.exports = CONSTANTS
